@baseUrl=http://localhost:8080/api/subscriber

### login
POST {{baseUrl}}/login
Content-Type: application/x-www-form-urlencoded

username = sample@gmail.com &
password = pwd00

### xx
GET {{baseUrl}}/login
