name: Spring demo CI

on:
  push:
    branches: [ rrr ]
#    branches: [ "release/spring" ]

jobs:
  build:

    runs-on: ubuntu-latest
    # permissions:
    #   contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: set props
      working-directory: java/demo
      run: echo "${{secrets.SECURITY_YML}}" > ./src/main/resources/security.yml

    - name: print info
      working-directory: java/demo
      run: |
        pwd
        ls -al
        echo "${{secrets.WAS}}"

    - name: setup ssh
      run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.WAS }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          echo ~/.ssh/known_hosts

    # - name: scp jar to was
    #   run: |
    #       scp java/demo/security.yml ec2-user@${{ secrets.WAS }}:/home/ec2-user/workspace/hanax/security.yml

    # - name: Setup Gradle
    #   uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    # - name: Build with Gradle Wrapper
    #   working-directory: java/demo
    #   run: ./gradlew clean build

